### ISSUE TITLE
Develop Dapper UI

### ISSUE THREAD

**Issue by justinffortier** [XYOracleNetwork/tool-dapper-react#1]
Task to develop UI for (Dapper)

**Comment by justinxyo** [comment]
➤ Paola Batiz commented:

@Kevin Weiler Hey kevin! saw this on my radar and wanted to see how much time i should allocate to this next week. I wanna make sure we have enough time to make it RAD :) thanks!!

**Comment by justinxyo** [comment]
➤ Kevin Weiler commented:

Just a heads up, it's probably going to be released as Beta as well, so we don't have to sweat it being perfect. I'll shoot you a demo video once i get all the initial functionality implemented early next week and we can discuss further if you want?

**Comment by justinxyo** [comment]
➤ Justin Fortier commented:

@Kevin Weiler@Paola Batiz I am pushing this back a week or so. The interface is not horrible right now given the utiilty of the tool. Kevin, you can just keep improving functionality and in the first week of September we can talk about the UI. 

PS Kevin, be sure to use the "@" to mention people otherwise they don't really see your comment :)

**Comment by justinxyo** [comment]
➤ Kevin Weiler commented:

Will do thanks @Justin Fortier

**Comment by justinffortier** [comment]
➤ Justin Fortier commented:

@Kevin Weiler Is design approved? You are just moving on to developing out the React components right?

**Comment by justinffortier** [comment]
➤ Kevin Weiler commented:

Yes, design looks fantastic! Thanks @Paola Batiz

**Comment by justinffortier** [comment]
➤ Paola Batiz commented:

@Justin Fortier@Kevin Weiler can i call this complete?

**Comment by justinffortier** [comment]
➤ Justin Fortier commented:

@Paola Batiz Kevin still needs to finish developing the UI. So I took you off and changed the task name

**Comment by justinffortier** [comment]
➤ Paola Batiz commented:

@Justin Fortier ok sweet, just checking if I needed anyhting else on here
