### ISSUE TITLE
.abiserver

### ISSUE THREAD

**Issue by arietrouw** [XYOracleNetwork/tool-dapper-react#18]
Should this file (.abiserver) be in the git ignore?  When using the dapper tool, it changes my file, so it is marked as dirty in git, but it looks like it is a config specific to me?

**Comment by maryannxy** [comment]
@jordantrouw Who are the preferable assignees for LayerOne tasks? Right now I'm hitting Kevin with this stuff but I want to make sure each task is going to the correct Sacramentan.

**Comment by klivin** [comment]
Removed this file and the concept of state saving server in lieu of cookies, and adding drag and drop to add your ABI
